### ISSUE TITLE
Would love to not have to provide the `env` variable

### ISSUE THREAD

**Issue by yoshutch** [byu-oit/terraform-aws-acs-info#13]
I know this is on the ACS side of things, but it would be nice to have the module already know what env it is in instead of us having to pass in `dev` or `prd` explicitly.

It's might be possible to glean this information from parsing the account name, but it might be nice to have an SSM param that states what env we're in.

**Comment by joshgubler** [comment]
Things that make sense from our perspective as "OIT Product account users" doesn't always make sense from the broader perspective of the cloud office. The problem here is that some accounts have many VPCs shared with them. `byu-org-platform`, and the monitoring accounts are the main ones. Probably others too.

**Comment by joshgubler** [comment]
This was fixed a long time ago!
